Revert "Merge pull request #1 from umamaheswararao/master"
This reverts commit 4e5a4022222fac4acab1f7719326945acc38ecc8, reversing
changes made to abd86b40911d0a641dcd9665ce6746c8ea90bac8.

found undefined reference to 'clock_gettime'